// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: company_api.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/httpbody"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *DeleteCompanyRes) Validate() error {
	return nil
}
func (this *CekCompanyIDAvaibilityReq) Validate() error {
	return nil
}
func (this *CompanySubsidiaryValidationReq) Validate() error {
	return nil
}
func (this *CompanySubsidiaryValidationRes) Validate() error {
	return nil
}
func (this *CheckCompanyIDTaskAndData) Validate() error {
	return nil
}
func (this *CekCompanyIDAvaibilityRes) Validate() error {
	return nil
}
func (this *TempGenToken) Validate() error {
	return nil
}
